# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: locust-worker
  labels:
    name: locust-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      serviceAccountName: sax-sa
      containers:
        - image: locust-load-generator 
          name: locust-worker
          command: ["locust"]
          args: ["-f", "/app/locustfile.py",  "--worker", "--master-host", "locust-master"]
          env:
            - name: LOCUST_MASTER
              value: locust-master
            - name: HUGGINGFACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hugging-face 
                  key: token
          envFrom:
            - configMapRef:
                name: locust-load-generator-parameters         
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi